apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular-app
spec:
  replicas: {{ .Values.angular.replicas }}
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
        - name: angular-app
          image: {{ .Values.angular.image }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.angular.service.port }}
          command: ["sh", "-c", "npm install && ng serve --proxy-config proxy.conf.json --host 0.0.0.0 --disable-host-check"]

---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: {{ .Values.angular.service.port }}
      targetPort: {{ .Values.angular.service.port }}
  type: NodePort
