apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ayurveda-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-app-service
                port:
                  number: {{ .Values.angular.service.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ayurveda-server-service
                port:
                  number: {{ .Values.backend.service.port }}
