apiVersion: v1
kind: Secret
metadata:
  name: ayurveda-secrets
  labels:
    app: ayurveda-server
type: Opaque
data:
  ayurveda_client_id: {{ .Values.secrets.ayurveda_client_id }}
  ayurveda_client_secret: {{ .Values.secrets.ayurveda_client_secret }}
  ayurveda_tenant_id: {{ .Values.secrets.ayurveda_tenant_id }}
  ayurveda_email_keyvault: {{ .Values.secrets.ayurveda_email_keyvault }}
  ayurveda_email: {{ .Values.secrets.ayurveda_email }}